meta_product_name: "ğŸš£â€â™‚ï¸ Kayapp"
meta_title: "ğŸš£â€â™‚ï¸ Kayapp - Practice kayak easier not harder!"
meta_description: "An application that merges all the data and gives access to a kayaker community."
meta_image: "cover.jpg" # should exist in `app/assets/images/...png`
